spring:
  data:
    mongodb:
        host: 192.168.59.103
        database: local

server:
  port: 8081

oauth:
  client:
        id: some-api
        secret: some-secret
jwt:
  keystore:
          key: mytestkey
          pass: changeme
          store:
              pass: letmein
          file:
              name: server.jks

logging:
    level:
      org:
        springframework:
                      web: INFO